modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/kaultakaulta75-dev/Tale-of-Kingdoms/issues"
license = "GPL-3.0"

[[mods]]
modId = "taleofkingdoms"
version = "${version}"
displayName = "Tale of Kingdoms: A New Conquest"
authors = "SamB440; NeoForge port by kaultakaulta75-dev"
credits = "Marackai, Aksel0206, PyroPyxel, Sheepguard, michaelb229, Krol05, BeingAmazing(Ben)"
description = '''
Experimental native NeoForge port for Minecraft 1.21.1.

Enter a dangerous realm of knights and honour, prove yourself to the Guildmaster,
complete quests, and forge your own kingdom.
'''
logoFile = "assets/taleofkingdoms/logo.png"

[[dependencies.taleofkingdoms]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.226,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.taleofkingdoms]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.taleofkingdoms]]
modId = "fabric_api"
type = "required"
versionRange = "[0.115.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.taleofkingdoms]]
modId = "cloth_config"
type = "required"
versionRange = "[15.0.140,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "taleofkingdoms.mixins.json"

[[mixins]]
config = "taleofkingdoms.client.mixins.json"
